{% set name = "hmmlearn" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d13a91ea3695df881465e3d36132d7eef4e84d483f4ba538a4b46e24b5ea100f

build:
  number: 0
  skip: true  # [py<38]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-build-isolation -vv
  missing_dso_whitelist:  # [s390x]
    - '$RPATH/ld64.so.1'  # [s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler("cxx") }}
  host:
    - pip
    - python
    - pybind11 >=2.6
    - setuptools
    - setuptools_scm >=3.3
    - wheel
  run:
    - python
    - scikit-learn >=0.16,!=0.22.0
    - numpy >=1.10
    - scipy >=0.19.0
    # mkl variant pulls in intel-openmp which conflicts with llvm-openmp. i.e. force to use openblas variant of numpy, scipy, etc.
    - blas=*=openblas  # [osx and x86_64]

test:
  imports:
    - hmmlearn
    - hmmlearn.tests
  commands:
    - pip check
    - python -I -mpytest --pyargs hmmlearn.tests -k "not test_fit_mcgrory_titterington1d"
  requires:
    - pip
    - pytest

about:
  home: https://github.com/hmmlearn/hmmlearn
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Hidden Markov Models in Python with scikit-learn like API.
  description: |
    hmmlearn is a set of algorithms for unsupervised learning and inference of Hidden Markov Models.
    For supervised learning learning of HMMs and similar models see seqlearn.
  doc_url: https://hmmlearn.readthedocs.io/
  dev_url: https://github.com/hmmlearn/hmmlearn

extra:
  recipe-maintainers:
    - npavlovikj
    - njzjz
  skip-lints:
    - version_constraints_missing_whitespace